name: 5. Follow Instagram Users

on:
  workflow_dispatch:

jobs:
  follow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use a specific Python version, e.g., '3.9' or '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run follow.py
      env:
        DECRYPT_KEY: ${{ secrets.DECRYPT_KEY }}
      run: python follow.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add config.json scraped_followers.json followed_unfollowed.json cookies.json.encrypted
        git commit -m "Automated: Update files after follow.py run" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
